[package]
name = "simd-lookup"
version = "0.1.0"
edition = "2024"

[dependencies]
simd_aligned = "0.6"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "table64_bench"
harness = false
